#!/usr/bin/env bash
# entrypoint for the panel container — first-boot install + boot.
#
# Post-runtime-swap layout: nginx + php-fpm decommissioned. The
# previous version of this script generated a php-fpm pool config
# (PHP_FPM_PM_MODE / PHP_FPM_MAX_CHILDREN / etc.); FrankenPHP's
# Octane wrapper handles the worker pool internally and reads its
# tunables from the OCTANE_* env namespace (see .env.example +
# docker-compose.yml). Pool generation is gone; everything else
# (composer install, key:generate, migrate, seed, asset publish,
# cache builds, initial render) is unchanged.
set -euo pipefail

cd /var/www/html

# Clear the entrypoint-complete sentinel before doing any work.
# Pre-fix: the v0.0.27 sentinel comment claimed "/tmp is tmpfs in
# this container, so the sentinel auto-clears on restart." That
# claim is FALSE — /tmp lives in the writable layer, NOT a tmpfs
# mount (no `tmpfs:` declaration in docker-compose.yml or the
# Dockerfile). On `docker compose restart panel` the sentinel
# survives, and any concurrent `install.sh` waiter that polls
# the sentinel returns "complete" before the new entrypoint run
# has actually finished its work — operator races. Removing the
# sentinel UP FRONT (vs. only at the end) flips the contract:
# absence-of-sentinel ALWAYS means "entrypoint in progress or
# crashed"; presence-of-sentinel ALWAYS means "this run finished
# cleanly." Round-7 audit fix.
rm -f /tmp/cool-tunnel/entrypoint-complete

# Make sure composer can write the home dir.
export COMPOSER_HOME=/tmp/composer
mkdir -p "$COMPOSER_HOME" storage/framework/{cache,sessions,views} storage/logs bootstrap/cache

# Hand storage/ + bootstrap/cache/ to www-data. The entrypoint runs
# as root (so we can write into bind-mounted volumes whose host
# ownership we don't control). Pre-swap: PHP-FPM workers ran as
# www-data per the FPM pool config and needed write access to
# Blade-compiled views + bootstrap cache. Post-swap: FrankenPHP's
# Octane process runs as the image's default user (root in
# dunglas/frankenphp:1-alpine), but we keep the chown for
# defensive consistency — Filament's published assets and any
# operator-side `docker compose exec panel ...` commands still
# expect www-data ownership for parity with prior deployments.
chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true
chmod -R 0775 storage bootstrap/cache 2>/dev/null || true

# ct-server-core daemon's unix-socket lives under /run/cool-tunnel.
# Pre-create with mode 0770 so supervisord's daemon program can bind.
mkdir -p /run/cool-tunnel && chmod 0770 /run/cool-tunnel || true

# First-boot OR composer.lock-drift: pull dependencies.
#
# Pre-FrankenPHP-swap this only fired when vendor/ was missing.
# That broke the FrankenPHP swap deploy — the host's vendor/ from
# the prior deploy didn't include laravel/octane, the entrypoint
# skipped install, and the panel boot crashed at config/octane.php
# with `Class "Laravel\Octane\Octane" not found`. The fix: also
# re-install when composer.lock is NEWER than vendor/autoload.php.
# That mtime-comparison catches every "lock changed since last
# install" path (PR merge, manual lock edit, dependency bump)
# without paying the install cost on every container boot — the
# common case (vendor/ already current) is one stat() syscall.
#
# Supply-chain hardening (v0.0.16): pass --no-scripts to composer.
# Without it, every transitive package's post-install /
# post-autoload-dump hook would execute as the panel user with
# full filesystem + DB access on every fresh container start. The
# project's own composer.json registers two known scripts via
# post-autoload-dump (`Illuminate\\Foundation\\ComposerScripts::
# postAutoloadDump` + `php artisan package:discover --ansi`); we
# explicitly invoke `package:discover` after install rather than
# letting any hook run blanket.
needs_install=0
if [ ! -d vendor ]; then
    echo "[entrypoint] vendor/ missing — running composer install"
    needs_install=1
elif [ composer.lock -nt vendor/autoload.php ]; then
    echo "[entrypoint] composer.lock newer than vendor/ — running composer install"
    needs_install=1
fi
if [ "$needs_install" = "1" ]; then
    composer install \
        --no-dev \
        --no-interaction \
        --prefer-dist \
        --optimize-autoloader \
        --no-scripts
fi

# Run package:discover UNCONDITIONALLY — not just after a fresh
# install. Caught by the FrankenPHP-runtime-swap deploy: the
# operator's manual `composer install --no-scripts` populated
# vendor/ with laravel/octane, but `bootstrap/cache/packages.php`
# (Laravel's package-discovery cache) was generated by a PRIOR
# entrypoint run that ran BEFORE octane was installed. The
# subsequent supervisord octane:start failed with `There are no
# commands defined in the "octane" namespace` because the cache
# didn't know octane existed. The original code ran package:
# discover ONLY inside the install branch; running it always
# (cheap, ~100 ms, idempotent) decouples cache freshness from the
# install path so manual / out-of-band installs heal too.
#
# Self-heal: if discover fails (e.g. corrupted services.php from
# an interrupted prior boot), drop the discovery cache and retry
# once. A second failure is genuine — supervisord still starts
# (entrypoint never blocks the boot), but the operator gets a
# clear diagnostic on stderr instead of a silent stale-cache
# state.
if ! php artisan package:discover --ansi; then
    echo "[entrypoint] package:discover failed — clearing stale cache + retry" >&2
    rm -f bootstrap/cache/packages.php bootstrap/cache/services.php
    php artisan package:discover --ansi || \
        echo "[entrypoint] WARN: package:discover failed twice — booting with last-known cache" >&2
fi

# Generate APP_KEY if it isn't set.
if ! grep -q '^APP_KEY=base64:' .env 2>/dev/null; then
    echo "[entrypoint] APP_KEY missing — generating"
    php artisan key:generate --force
fi

# Wait for the database before migrating. We retry up to 60s.
for i in $(seq 1 30); do
    if php artisan db:show >/dev/null 2>&1; then
        break
    fi
    echo "[entrypoint] waiting for db ($i/30)…"
    sleep 2
done

# Capture migrate exit code. Pre-fix this was `... || true`,
# which masked partial-migration failures: if migration N+1
# blew up after migration N+0 had committed, the schema was
# half-applied, the entrypoint continued, supervisord brought
# FrankenPHP up, /up returned 200, the docker healthcheck went
# green, and every panel request to a column that didn't exist
# yet 500'd. Operator saw "container healthy, panel broken"
# with no obvious diagnostic. Round-6 ops audit fix.
#
# Failure handling: write a sentinel file the operator can
# inspect (`docker compose exec panel cat /tmp/cool-tunnel/
# migrate-failed`), surface a loud stderr line, and DO continue
# the boot — a crashing entrypoint creates a worse failure mode
# (supervisord never starts; container restart-loops without
# even the diagnostic). The sentinel is the operator-facing
# signal.
mkdir -p /tmp/cool-tunnel
rm -f /tmp/cool-tunnel/migrate-failed
if ! php artisan migrate --force --no-interaction; then
    rc=$?
    echo "[entrypoint] WARN: migrate exited with code $rc — schema may be half-applied" >&2
    echo "[entrypoint] WARN: panel will boot, but model queries may 500 on missing columns" >&2
    echo "[entrypoint] WARN: inspect: docker compose logs panel | grep 'WARN:'" >&2
    date -u +'%Y-%m-%dT%H:%M:%SZ' > /tmp/cool-tunnel/migrate-failed
fi

# Seed the singleton ServerConfig row + the default cover-site
# template. Both paths are idempotent (ServerConfig::current() is
# firstOrCreate on id=1, FakeWebsite::create runs only when
# count()===0), so this is safe to run on every boot — and required
# to run BEFORE the renderer below. Without this seed pass on first
# boot, the renderer crashes with "no rows returned by a query that
# expected to return at least one row" because server_configs.id=1
# doesn't exist yet, leaving Caddyfile empty and Caddy unable to
# fetch a TLS cert. install.sh also runs db:seed (after the
# migrate-status check) but that path would fail-open if the
# renderer needs the seed before install.sh gets a chance —
# duplicating it here closes the gap. (v0.0.27 hotfix.)
php artisan db:seed --force --no-interaction || true

php artisan filament:cache-components --no-interaction || true

# Publish Filament's CSS/JS assets to public/css/filament/ + public/
# js/filament/. Filament 3 ships these inside the package; the
# panel's Blade layout references them at /css/filament/... .
# Without this step the files don't exist on first boot and the
# panel renders as a wall of unstyled HTML. `filament:assets` is
# idempotent. (v0.0.29 hotfix.)
php artisan filament:assets --no-interaction || true

php artisan config:cache  --no-interaction || true
php artisan route:cache   --no-interaction || true

# Clear stale Blade-compiled views before re-baking the cache.
# Pre-fix `view:cache` only re-rendered templates it discovered;
# orphan compiled-view files from removed Blade templates (or
# from a prior PHP-version era — e.g., upgrading PHP 8.3 → 8.4
# in the FrankenPHP swap) survived in storage/framework/views/.
# Under Octane's per-worker container reuse, a stale compiled
# view that references a service binding from the FPM era could
# resolve at request time against the new container. Low actual
# risk (Filament 3 + Livewire 3 are Octane-clean, no custom
# bindings observed) but free hygiene. Round-7 audit follow-up.
rm -rf storage/framework/views/* 2>/dev/null || true
php artisan view:cache    --no-interaction || true

# Render the initial Caddyfile + sing-box config from the DB so both
# servers have something to load on first boot. The CaddyfileGenerator
# writes to /etc/caddy (mounted from caddy_etc volume), the
# SingBoxConfigGenerator writes to /etc/sing-box (singbox_etc).
php artisan caddyfile:render --no-interaction || true
php artisan singbox:render   --no-interaction || true

# Sentinel for install.sh — signals first-boot setup (composer +
# migrate + cache + render) is finished and it's safe to query
# state without racing the entrypoint. v0.0.26 race-fix: install.sh
# previously ran its own `migrate` immediately after
# `vendor/autoload.php` appeared, which raced this entrypoint's
# migrate above and crashed with "Table 'cache' already exists".
#
# The sentinel is `rm -f`'d at the TOP of this script (see the
# round-7-audit comment near line 14). Absence-of-sentinel ==
# "entrypoint in progress or crashed"; presence == "this run
# finished cleanly." Don't rely on /tmp being tmpfs — it isn't,
# in this container.
mkdir -p /tmp/cool-tunnel
: >/tmp/cool-tunnel/entrypoint-complete

exec "$@"
